// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.api.ads.adwords.keywordoptimizer.formula;

/**
 * This class is auto-generated by jjTree and contains grammar constants representing tree nodes.
 */
public interface FormulaParserTreeConstants {
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTINTEGER = 5;
  public int JJTDOUBLE = 6;

  public String[] jjtNodeName = {
    "Expression", "void", "Add", "Mult", "Identifier", "Integer", "Double",
  };
}
